### ISSUE TITLE
The advice of wasetime

### ISSUE THREAD

**Issue by Lmmmmm** [wasetime/wasetime-web#15]
1.Memo
As a basic function of timetable, we often use the memo function on this app.
(We can also add schedule and Attendance function)

2.Help Feature
If we continue to use this app in the second year, we may forget the instruction. So we can add a “help” button to help the user who forget the instruction.

3.About Evaluation(a little difficult)
In my opinion, Japanese students often add evaluation at timetable(such as test 100%, report 50%+attendance50%).  So it is better that if we can add this feature.

**Comment by OscarWang114** [comment]
Hi @Lmmmmm , thank you very much for this issue. 👍 
Could you help me split the three pieces of advice that you mentioned into three separate issues and post it on github again? Thanks!

**Comment by OscarWang114** [comment]
Thanks for #16 #17 #18 . I'm closing this issue.
